### ISSUE TITLE
Measurement Model error ?

### ISSUE THREAD

**Issue by mengchaoheng** [arplaboratory/GeomInertiaEstimator#4]
Measurement Model (18) in paper, about acceleration is error? 

in the line 521 of `geom_inertia_estimator.cpp` of code, it should be minus `Omega_dot.cross(r_MI)` ,  and so as the equ(18) in paper.
![截屏2024-07-18 17 31 05](https://github.com/user-attachments/assets/b9796f04-8407-41da-b6b6-0df05618d1f9)

![截屏2024-07-18 17 32 28](https://github.com/user-attachments/assets/115406ce-d39a-4528-8b5a-9d91dbe39b77)

**Comment by mengchaoheng** [comment]
Is it ENU frame in the paper? @vwueest

**Comment by mengchaoheng** [comment]
@loiannog

**Comment by vwueest** [comment]
Hi @mengchaoheng . Thanks for your interest. Why do you think it should be minus? Do you have any reference or derivation that lead you to this conclusion?

Yes, we use ENU in this paper

**Comment by mengchaoheng** [comment]
@vwueest  Thank you for your reply, your work is exciting and quite practical. I will give my explanation about the measurement model later. Both models converge in the end. 


Now my more pressing problem is the coordinate system problem. I plan to use your work in conjunction with PX4, and I have encountered a coordinate system conversion problem. I don't know how your aircraft coordinate system is defined. Specifically, I want to know the relationship between ENU and the four motors, that is, which direction is the x-axis and which axis is the forward flight direction of the aircraft? Is the imu measurement value [0 0 9.8] when the aircraft is stationary? Because PX4 has clear definitions for them, I need to compare them carefully before combining them. Forgive me for asking so many questions.

**Comment by mengchaoheng** [comment]
The conversion of px4 from ned to enu coordinate system is to swap x and y, and then reverse the setting of z. Since I cannot judge the specific details of the data set(config/lissajous_trajectory.bag ), I cannot give the exact data flow of px4 to your project.

**Comment by mengchaoheng** [comment]
I'm waiting for your help @vwueest . SOS

**Comment by vwueest** [comment]
It was night where I currently am. I will answer as soon as I can, so no need to send an extra SOS message.

I stand corrected about the ENU, sorry, I meant to say it is x - forward, y - left, z - up.

The accelerometer measurement are rotated to this frame when being read. You can find this in the config file [here](https://github.com/arplaboratory/GeomInertiaEstimator/blob/master/config/quad_params.yaml#L53). At rest, the accelerometer should therefore be [0, 0, 9.81] and then be rotated in the code [here](https://github.com/arplaboratory/GeomInertiaEstimator/blob/master/src/geom_inertia_estimator.cpp#L712) to [0, 0, -9.81]. Since it has been 5 years I would need to verify with the bag file, but I don't have a computer handy at the moment. You could verify this by reading measurements of the IMU at the start of the bag file. Let me know if you have some insights in this regard.

The rotor positions and induced moment direction you find [here](https://github.com/arplaboratory/GeomInertiaEstimator/blob/master/config/quad_params.yaml#L56).

I hope that helps

**Comment by mengchaoheng** [comment]
A new [fork](https://github.com/mengchaoheng/GeomInertiaEstimator.git) of this is update. 

I ignored the model issue for now and got the ros node running, and it seems to be working as expected.

**Comment by mengchaoheng** [comment]
can you pass me your doctoral thesis? @vwueest 
<Accurate and agile flight with winged drones>

it is very nice of you.

**Comment by vwueest** [comment]
Awesome! Thanks for the hint. I think I'll pull in the updates on the plotjuggler layout file.

If you think you have it running well on PX4 you can let me know and I can add a reference to your fork in the README here. That could be very useful for other people too.

Regarding my thesis: This paper was before my PhD. My PhD thesis is focused on using vision and morphing wings on drones to achieve accurate and agile flight like birds. So quite different from what we did in this work. If you're still interested, let me know, I'll gladly send it over if it helps :)

**Comment by mengchaoheng** [comment]
> If you think you have it running well on PX4 you can let me know and I can add a reference to your fork in the README here. 

Yes, it work well. Although it seems that it requires a lot of configuration on the px4 and mavros side, it is actually just a few lines of code modification. This project can be used by just modifying the parameters. For details, please see my updated [readme](https://github.com/mengchaoheng/GeomInertiaEstimator?tab=readme-ov-file#px4-example).
